# Generated by Django 6.0.1 on 2026-03-04 12:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Boxer",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("middle_name", models.CharField(blank=True, max_length=30)),
                ("birth_date", models.DateField()),
                (
                    "sex",
                    models.CharField(
                        choices=[("B", "Мальчик"), ("G", "Девочка")], max_length=1
                    ),
                ),
                (
                    "rank",
                    models.CharField(
                        choices=[("A", "A"), ("B", "B"), ("C", "C")], max_length=1
                    ),
                ),
                ("weight", models.DecimalField(decimal_places=1, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name="BoxerRoom",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("middle_name", models.CharField(blank=True, max_length=30)),
                ("birth_date", models.DateField()),
                ("age", models.PositiveIntegerField()),
                (
                    "sex",
                    models.CharField(
                        choices=[("B", "Мальчик"), ("G", "Девочка")], max_length=1
                    ),
                ),
                (
                    "rank",
                    models.CharField(
                        choices=[("A", "A"), ("B", "B"), ("C", "C")], max_length=1
                    ),
                ),
                ("weight", models.DecimalField(decimal_places=1, max_digits=5)),
                ("weight_category", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Fight",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Ring",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1)),
                ("description", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("0", "Подготовка"),
                            ("Y", "Активно"),
                            ("N", "Не используется"),
                        ],
                        default="0",
                        max_length=1,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("start_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("0", "Подготовка"),
                            ("Y", "Активно"),
                            ("N", "Завершено"),
                        ],
                        default="0",
                        max_length=1,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RoomApplication",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("0", "Ожидает"),
                            ("Y", "Одобрено"),
                            ("N", "Отказано"),
                        ],
                        default="0",
                        max_length=1,
                    ),
                ),
            ],
        ),
    ]
