# Generated by Django 6.0.1 on 2026-03-22 18:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Boxer",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("middle_name", models.CharField(blank=True, max_length=30)),
                ("birth_date", models.DateField()),
                (
                    "sex",
                    models.CharField(
                        choices=[("B", "Мальчик"), ("G", "Девочка")], max_length=1
                    ),
                ),
                (
                    "rank",
                    models.CharField(
                        choices=[("A", "A"), ("B", "B"), ("C", "C")], max_length=1
                    ),
                ),
                ("weight", models.DecimalField(decimal_places=1, max_digits=4)),
                (
                    "trainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boxers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BoxerRoom",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("middle_name", models.CharField(blank=True, max_length=30)),
                ("birth_date", models.DateField()),
                ("age", models.PositiveIntegerField()),
                (
                    "sex",
                    models.CharField(
                        choices=[("B", "Мальчик"), ("G", "Девочка")], max_length=1
                    ),
                ),
                (
                    "rank",
                    models.CharField(
                        choices=[("A", "A"), ("B", "B"), ("C", "C")], max_length=1
                    ),
                ),
                ("weight", models.DecimalField(decimal_places=1, max_digits=4)),
                ("weight_category", models.CharField(max_length=20)),
                ("is_available", models.BooleanField(default=True)),
                (
                    "source_boxer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="referee.boxer",
                    ),
                ),
                (
                    "trainer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="boxers_room",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("description", models.TextField(blank=True, max_length=50)),
                ("start_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("0", "Подготовка"),
                            ("Y", "Активно"),
                            ("N", "Завершено"),
                        ],
                        default="0",
                        max_length=1,
                    ),
                ),
                (
                    "boss",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boss_rooms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ring",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1)),
                ("description", models.CharField(blank=True, max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[("Y", "Используется"), ("N", "Не используется")],
                        default="N",
                        max_length=1,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rings",
                        to="referee.room",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Fight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                (
                    "stage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1/32", "1/32"),
                            ("1/16", "1/16"),
                            ("1/8", "1/8"),
                            ("1/4", "1/4"),
                            ("1/2", "1/2"),
                            ("final", "Финал"),
                        ],
                        max_length=5,
                        null=True,
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wins",
                        to="referee.boxerroom",
                    ),
                ),
                (
                    "ring",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fights",
                        to="referee.ring",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fights",
                        to="referee.room",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="boxerroom",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="boxers_room",
                to="referee.room",
            ),
        ),
        migrations.CreateModel(
            name="RoomApplication",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("0", "Ожидает"),
                            ("Y", "Одобрено"),
                            ("N", "Отказано"),
                        ],
                        default="0",
                        max_length=1,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms_applications",
                        to="referee.room",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="room",
            name="trainers",
            field=models.ManyToManyField(
                related_name="rooms_as_trainer",
                through="referee.RoomApplication",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="FightSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "corner",
                    models.CharField(
                        choices=[("blue", "Синий"), ("red", "Красный")], max_length=4
                    ),
                ),
                (
                    "boxer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fight_slots",
                        to="referee.boxerroom",
                    ),
                ),
                (
                    "fight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="referee.fight",
                    ),
                ),
                (
                    "source_fight",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_slots",
                        to="referee.fight",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("fight", "corner"), name="uniq_fight_corner"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="ring",
            constraint=models.UniqueConstraint(
                fields=("room", "name"), name="unique_ring_name_per_room"
            ),
        ),
        migrations.AddConstraint(
            model_name="ring",
            constraint=models.CheckConstraint(
                condition=models.Q(("name__in", ["A", "B", "C", "D", "E"])),
                name="ring_name_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="roomapplication",
            constraint=models.UniqueConstraint(
                fields=("room", "user"), name="uniq_room_user"
            ),
        ),
    ]
