# Generated by Django 6.0.1 on 2026-03-16 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("referee", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="boxer",
            name="trainer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="boxers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="boxerroom",
            name="source_boxer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="referee.boxer",
            ),
        ),
        migrations.AddField(
            model_name="boxerroom",
            name="trainer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="boxers_room",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="fight",
            name="winner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="wins",
                to="referee.boxerroom",
            ),
        ),
        migrations.AddField(
            model_name="fightslot",
            name="boxer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fight_slots",
                to="referee.boxerroom",
            ),
        ),
        migrations.AddField(
            model_name="fightslot",
            name="fight",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="slots",
                to="referee.fight",
            ),
        ),
        migrations.AddField(
            model_name="fightslot",
            name="source_fight",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="target_slots",
                to="referee.fight",
            ),
        ),
        migrations.AddField(
            model_name="fight",
            name="ring",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fights",
                to="referee.ring",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="boss",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="boss_rooms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ring",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rings",
                to="referee.room",
            ),
        ),
        migrations.AddField(
            model_name="fight",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fights",
                to="referee.room",
            ),
        ),
        migrations.AddField(
            model_name="boxerroom",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="boxers_room",
                to="referee.room",
            ),
        ),
        migrations.AddField(
            model_name="roomapplication",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rooms_applications",
                to="referee.room",
            ),
        ),
        migrations.AddField(
            model_name="roomapplication",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_applications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="trainers",
            field=models.ManyToManyField(
                related_name="rooms_as_trainer",
                through="referee.RoomApplication",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="fightslot",
            constraint=models.UniqueConstraint(
                fields=("fight", "corner"), name="uniq_fight_corner"
            ),
        ),
        migrations.AddConstraint(
            model_name="ring",
            constraint=models.UniqueConstraint(
                fields=("room", "name"), name="unique_ring_name_per_room"
            ),
        ),
        migrations.AddConstraint(
            model_name="ring",
            constraint=models.CheckConstraint(
                condition=models.Q(("name__in", ["A", "B", "C", "D", "E"])),
                name="ring_name_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="roomapplication",
            constraint=models.UniqueConstraint(
                fields=("room", "user"), name="uniq_room_user"
            ),
        ),
    ]
