# Generated by Django 6.0.1 on 2026-03-31 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("referee", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="ring",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="groups",
                to="referee.ring",
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="groups",
                to="referee.room",
            ),
        ),
        migrations.AlterField(
            model_name="groupboxer",
            name="boxer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="groups",
                to="referee.boxerroom",
            ),
        ),
        migrations.AlterField(
            model_name="groupboxer",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="boxers",
                to="referee.group",
            ),
        ),
    ]
