# Generated by Django 6.0.1 on 2026-04-06 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("referee", "0003_alter_group_ring_alter_group_room_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomapplication",
            name="boxers",
            field=models.ManyToManyField(
                related_name="applications", to="referee.boxer"
            ),
        ),
    ]
